/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopFitoutsRouteImport } from './routes/shop-fitouts'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CustomKitchensRouteImport } from './routes/custom-kitchens'
import { Route as CustomCabinetryJoineryRouteImport } from './routes/custom-cabinetry-joinery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialProjectsRouteImport } from './routes/commercial-projects'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ShopFitoutsRoute = ShopFitoutsRouteImport.update({
  id: '/shop-fitouts',
  path: '/shop-fitouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomKitchensRoute = CustomKitchensRouteImport.update({
  id: '/custom-kitchens',
  path: '/custom-kitchens',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCabinetryJoineryRoute = CustomCabinetryJoineryRouteImport.update({
  id: '/custom-cabinetry-joinery',
  path: '/custom-cabinetry-joinery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialProjectsRoute = CommercialProjectsRouteImport.update({
  id: '/commercial-projects',
  path: '/commercial-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/commercial-projects': typeof CommercialProjectsRoute
  '/contact': typeof ContactRoute
  '/custom-cabinetry-joinery': typeof CustomCabinetryJoineryRoute
  '/custom-kitchens': typeof CustomKitchensRoute
  '/faqs': typeof FaqsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/services': typeof ServicesRoute
  '/shop-fitouts': typeof ShopFitoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-projects': typeof CommercialProjectsRoute
  '/contact': typeof ContactRoute
  '/custom-cabinetry-joinery': typeof CustomCabinetryJoineryRoute
  '/custom-kitchens': typeof CustomKitchensRoute
  '/faqs': typeof FaqsRoute
  '/services': typeof ServicesRoute
  '/shop-fitouts': typeof ShopFitoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/blog': typeof BlogIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/commercial-projects': typeof CommercialProjectsRoute
  '/contact': typeof ContactRoute
  '/custom-cabinetry-joinery': typeof CustomCabinetryJoineryRoute
  '/custom-kitchens': typeof CustomKitchensRoute
  '/faqs': typeof FaqsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/services': typeof ServicesRoute
  '/shop-fitouts': typeof ShopFitoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/commercial-projects'
    | '/contact'
    | '/custom-cabinetry-joinery'
    | '/custom-kitchens'
    | '/faqs'
    | '/portfolio'
    | '/services'
    | '/shop-fitouts'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/blog/'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commercial-projects'
    | '/contact'
    | '/custom-cabinetry-joinery'
    | '/custom-kitchens'
    | '/faqs'
    | '/services'
    | '/shop-fitouts'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/blog'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/commercial-projects'
    | '/contact'
    | '/custom-cabinetry-joinery'
    | '/custom-kitchens'
    | '/faqs'
    | '/portfolio'
    | '/services'
    | '/shop-fitouts'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/blog/'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CommercialProjectsRoute: typeof CommercialProjectsRoute
  ContactRoute: typeof ContactRoute
  CustomCabinetryJoineryRoute: typeof CustomCabinetryJoineryRoute
  CustomKitchensRoute: typeof CustomKitchensRoute
  FaqsRoute: typeof FaqsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  ShopFitoutsRoute: typeof ShopFitoutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop-fitouts': {
      id: '/shop-fitouts'
      path: '/shop-fitouts'
      fullPath: '/shop-fitouts'
      preLoaderRoute: typeof ShopFitoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-kitchens': {
      id: '/custom-kitchens'
      path: '/custom-kitchens'
      fullPath: '/custom-kitchens'
      preLoaderRoute: typeof CustomKitchensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cabinetry-joinery': {
      id: '/custom-cabinetry-joinery'
      path: '/custom-cabinetry-joinery'
      fullPath: '/custom-cabinetry-joinery'
      preLoaderRoute: typeof CustomCabinetryJoineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-projects': {
      id: '/commercial-projects'
      path: '/commercial-projects'
      fullPath: '/commercial-projects'
      preLoaderRoute: typeof CommercialProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CommercialProjectsRoute: CommercialProjectsRoute,
  ContactRoute: ContactRoute,
  CustomCabinetryJoineryRoute: CustomCabinetryJoineryRoute,
  CustomKitchensRoute: CustomKitchensRoute,
  FaqsRoute: FaqsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ServicesRoute: ServicesRoute,
  ShopFitoutsRoute: ShopFitoutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
